# Generated by Django 4.2.6 on 2024-02-08 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/upload/')),
                ('Description', models.CharField(max_length=120)),
                ('price', models.CharField(max_length=50)),
            ],
        ),
    ]
