# Generated by Django 5.0.1 on 2024-03-08 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_hotel_rooms_alter_packages_price_packages_hotel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='room',
        ),
    ]
