# Generated by Django 5.0.1 on 2024-03-08 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_remove_hotel_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packages',
            name='hotel',
        ),
    ]
