# Generated by Django 4.2.6 on 2024-02-20 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0002_profile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pfp',
            field=models.ImageField(default='images/default/Default_pfp.jpg', upload_to=''),
        ),
    ]
